version: '3.8'
services:

  postgres_db:
    image: postgres:14-alpine
    env_file: 
      - ./server/.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=foodie
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres_db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: 
      - ./server/.env
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_TOKEN_JWT_SECRET=${ACCESS_TOKEN_JWT_SECRET}
      - REFRESH_TOKEN_JWT_SECRET=${REFRESH_TOKEN_JWT_SECRET}
    depends_on:
      - postgres_db
    ports:
      - 4000:4000
    restart: always
    command: 'npm start'
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    command: npm start
    container_name: client
