# version: '3.8'

# services:
#   # db:
#   #   container_name: postgres
#   #   image: postgres:14.1-alpine
#   #   restart: always
#   #   ports:
#   #     - '5432:5432'
#   #   environment:
#   #     - POSTGRES_USER=root
#   #     - POSTGRES_PASSWORD=root
#   #     - POSTGRES_DB=foodie

#   server:
#     container_name: server
#     image: node:16.16.0-alpine
#     restart: always
#     build:
#       context: .
#       dockerfile: ./server/Dockerfile
#     ports:
#       - '4000:4000'
#     # environment:
#     #   DATABASE_URL: postgres://root:root@postgres:5432/db
#     #   NODE_ENV: development
#     #   PORT: 4000
#     # depends_on:
#     #   - db
#     command: npm start
#     volumes:
#       - .:/app/
#       - /app/node_modules


#   # pgadmin:
#   #   container_name: pgadmin
#   #   image: dpage/pgadmin4
#   #   restart: always
#   #   ports:
#   #     - "5050:80"
#   #   environment:
#   #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#   #     - PGADMIN_DEFAULT_PASSWORD=root
#   #   depends_on:
#   #     - db
